### PR TITLE
Add BowerCDN link for install

### PR DESCRIPTION
**Pull request by nullivex**
This option helps people use a install free way of using bower packages and is backed through Cloudflare and redundant servers.

I hope you will accept this option.

### CODE REVIEW

**Comment by rodneyrehm** [comment]
I didn't know of bowercdn, nice!
could I trouble you to re-open the PR against master instead of gh-pages?

**Comment by ooxi** [comment]
This is slightly off topic but I have never heard of bowercdn. Could you provide any information about that service?

**Comment by nullivex** [comment]
@ooxi Sorry, I spaced this out completely.

I got tired of doing bower installs when I was working on projects. Then I was tired of trying to find cdn versions of bower packages independently. So I setup bowercdn where you can use whatever bower package you want and have it backed by Cloudflares CDN.

I have a blog written on the subject here: http://www.serverpals.com/blog/using-bower-with-bowercdn-for-better-web-performance

Let me know if you have any other questions.

**Comment by nullivex** [comment]
@rodneyrehm I will re-open the PR now.

**Comment by rodneyrehm** [comment]
… and merged. thanks!

**Pull request closed without merging**
