### PR TITLE
fixed #347 - added _ to the list of valid hostname chartacters

### LINKED ISSUE #347: can't parse a domain with underscore
banner

probably because of this code
```
  // allowed hostname characters according to RFC 3986
  // ALPHA DIGIT "-" "." "_" "~" "!" "$" "&" "'" "(" ")" "*" "+" "," ";" "=" %encoded
  // I've never seen a (non-IDN) hostname other than: ALPHA DIGIT . -
  URI.invalid_hostname_characters = /[^a-zA-Z0-9\.-]/;
```

### PR DESCRIPTION
**Pull request by vzaidman**

### CODE REVIEW

**Comment by vzaidman** [comment]
wrong branch

**Comment by rodneyrehm** [comment]
can you have a look at 9b05d56c4768232fcf0a4c51f6f38bcbce1d58c4 and pull that into your PR?

**Comment by vzaidman** [comment]
ok

**Comment by vzaidman** [comment]
@rodneyrehm updated the PR.

**Comment by rodneyrehm** [comment]
thank you! :)

**Comment by rodneyrehm** [comment]
released as [v1.18.12](https://github.com/medialize/URI.js/releases/tag/v1.18.12)

**Pull request merged**
