### PR TITLE
Check the module object itself for accessing module.exports

### LINKED ISSUE #318: Uncaught ReferenceError: module is not defined(…) on some sites
Hi! We use URI.js in a multi-browser extension that we are developing, and we are running into an issue on https://mochajs.org/ where URI.js tries to access modules.export when modules is undefined. This is because on this site, the exports variable is being used for something, so `if (typeof exports === 'object')` will return true when it shouldn't.

### PR DESCRIPTION
**Pull request by mttwc**
On some sites, the `exports` variable is being used for other (non-node) things, resulting in the wrong code path being executed, leading to `Uncaught ReferenceError: module is not defined(…)`. This PR adds an additional check for the module object itself before trying to access it.

Fixes #318

### CODE REVIEW

**Comment by rodneyrehm** [comment]
Thank you!

Is there a reason to not go with `typeof module === 'object' && module.exports` instead, as [umd/returnExports.js](https://github.com/umdjs/umd/blob/master/templates/returnExports.js#L21) shows? I mean other than the original code testing for `typeof exports === 'object'` and this fix being the smallest possible change?

**Comment by mttwc** [comment]
Not that I can think of, good call :)
I'll amend it now!

**Comment by larsendaniel** [comment]
👍

**Comment by rodneyrehm** [comment]
Thank you!
Your fix has been released as [v1.18.3](https://github.com/medialize/URI.js/releases/tag/v1.18.3)

**Comment by mttwc** [comment]
Excellent! Thanks for being so quick on this!

**Pull request merged**
