### PR TITLE
removeQuery accepts RegExp that filters the keys

### PR DESCRIPTION
**Pull request by peterwillis**
I added RegExp support to the removeQuery function. It is a bit like passing a string, except if uses the regexp to filter out keys that match the expression. I added a test and updated the docs too.

### CODE REVIEW

**Comment by rodneyrehm** [comment]
is `removeQuery()` the only method where accepting a RegExp makes sense?

**Comment by peterwillis** [comment]
Yes, it is already supported by hasQuery, and I don't think it makes sense in add or set

**Comment by rodneyrehm** [comment]
I see [`.hasQuery()`](http://medialize.github.io/URI.js/docs.html#search-has) accepts a RegExp to validate the *value*, but not the *name*. Your PR would apply the RegExp to the *name*, but not the *value*.

Should both methods accept RegExps for both *name* and *value*?

**Comment by peterwillis** [comment]
I don't think so. When I look at changing hasQuery to support that, I don't know how it should behave. If the regexp matches multiple keys then should it test all the values? To make it support a regexp for the key parameter and also support all the other ways you can use it would be quite complex and I can't think of any use cases for it, so it would just be extra code for no reason. If you look at the way removeQuery works when you give it a single string, the way I have done it fits in nicely with that ie it filters the keys, not the values. I don't think it makes the overall API inconsistent.

**Comment by rodneyrehm** [comment]
> I don't think it makes the overall API inconsistent.

The one method accepts RegExp for keys, the other method accepts RegExp for values. How is that not inconsistent?

> … I can't think of any use cases for it, so it would just be extra code for no reason.

neither can I for the `hasQuery()` part. for the removeQuery supporting RegExp for values does make a bit more sense, though.

**Comment by peterwillis** [comment]
What I mean is that in hasQuery, the first parameter is the key selector, the second is the value selector, so if the first argument is always a key selector in the methods, the API is consistent.

I can appreciate that someone may want to filter out an option in the query if a value matches a regexp. That would be an additional way of using removeQuery where the value regexp is passed as the second argument, rather than a replacement for this.

I can submit that in another pr if it is also useful?

**Comment by rodneyrehm** [comment]
> I can appreciate that someone may want to filter out an option in the query if a value matches a regexp. 

yes, there was a time when I did this regularly. 

> I can submit that in another pr if it is also useful?

You could also just add it do this PR, after all it's just extending the RegExp support you introduced here, no?

**Comment by rodneyrehm** [comment]
I merged what you had and added the missing bit myself. thanks for your support!

**Pull request merged**
